name: tugas3
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/icons/leaf.png
  - assets/icons/notification.png
  - assets/icons/cool.png
  - assets/icons/happy-face.png
  - assets/icons/heart-eyes.png
  - assets/icons/sad-face.png
  - assets/images/ilustrasi.png
  
